name: Deploy Smart Village Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            echo "==============================="
            echo "Starting Smart Village Deploy"
            echo "==============================="

            cd ~/Smart-Village-Website

            echo "Cleaning repository..."
            git fetch origin
            git reset --hard origin/main
            git clean -fd

            echo "Backend"

            cd server

            npm ci

            pm2 restart smart-village-api

            cd ..

            echo "Frontend"

            cd client

            npm install

            npm run build

            echo "Updating Nginx files..."

            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            echo "Reloading Nginx..."

            sudo systemctl reload nginx

            echo "==============================="
            echo "Deployment Successful"
            echo "==============================="